# Generated by Django 3.2.5 on 2021-07-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(max_length=200)),
                ('player_bet', models.IntegerField(verbose_name=3)),
                ('player_hand', models.CharField(max_length=64)),
                ('dealer_hand', models.CharField(max_length=64)),
                ('player_bust', models.BooleanField(default=False)),
                ('dealer_bust', models.BooleanField(default=False)),
                ('player_chips', models.IntegerField(verbose_name=6)),
                ('blackjack', models.CharField(blank=True, choices=[('P', 'Player'), ('D', 'Dealer')], max_length=1)),
                ('hand_winner', models.CharField(blank=True, choices=[('P', 'Player'), ('D', 'Dealer')], max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
