# Generated by Django 3.2.5 on 2021-07-31 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dealer_hand',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_hand',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None),
        ),
    ]
