# Generated by Django 3.2.5 on 2021-08-02 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackjack_backend', '0002_auto_20210731_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='d_hand_val',
            field=models.IntegerField(default=0, verbose_name=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p_hand_val',
            field=models.IntegerField(default=0, verbose_name=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='payout',
            field=models.IntegerField(blank=True, default=0, verbose_name=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='auth.user'),
            preserve_default=False,
        ),
    ]
